=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module OpenapiClient
  class WhatsappPhoneNumberQualityRating
    GREEN = "GREEN".freeze
    YELLOW = "YELLOW".freeze
    RED = "RED".freeze
    UNKNOWN = "UNKNOWN".freeze

    def self.all_vars
      @all_vars ||= [GREEN, YELLOW, RED, UNKNOWN].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WhatsappPhoneNumberQualityRating.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WhatsappPhoneNumberQualityRating"
    end
  end
end
