=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for YCloudApiClient::BalanceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BalanceApi' do
  before do
    # run before each test
    @api_instance = YCloudApiClient::BalanceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BalanceApi' do
    it 'should create an instance of BalanceApi' do
      expect(@api_instance).to be_instance_of(YCloudApiClient::BalanceApi)
    end
  end

  # unit tests for balance_retrieve
  # Retrieve balance
  # Retrieves the current account balance.
  # @param [Hash] opts the optional parameters
  # @return [Balance]
  describe 'balance_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
