=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for YCloudApiClient::EmailsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EmailsApi' do
  before do
    # run before each test
    @api_instance = YCloudApiClient::EmailsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmailsApi' do
    it 'should create an instance of EmailsApi' do
      expect(@api_instance).to be_instance_of(YCloudApiClient::EmailsApi)
    end
  end

  # unit tests for email_send
  # Send an email
  # Sends an outbound email message.
  # @param email_send_request 
  # @param [Hash] opts the optional parameters
  # @return [Email]
  describe 'email_send test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
