=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SMSApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SMSApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SMSApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SMSApi' do
    it 'should create an instance of SMSApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SMSApi)
    end
  end

  # unit tests for sms_list
  # List SMS records
  # Returns a paginated list of SMS messages you&#39;ve previously sent.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number of the results to be returned, 1-based.
  # @option opts [Integer] :limit A limit on the number of results to be returned, or number of results per page, between 1 and 100, defaults to 10.
  # @option opts [Boolean] :include_total Return results inside an object that contains the total result count or not.
  # @option opts [Time] :filter_create_time_gte Return results where the &#x60;createTime&#x60; field is greater than or equal to this value. Default: One day ago from now.
  # @option opts [Time] :filter_create_time_lte Return results where the &#x60;createTime&#x60; field is less than or equal to this value.
  # @option opts [String] :filter_id Unique object ID on our side. Other filter parameters will be ignored if this parameter is present.
  # @return [SmsPage]
  describe 'sms_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sms_send
  # Send an SMS
  # Sends an outbound text message.
  # @param sms_send_request SMS request that needs to be sent.
  # @param [Hash] opts the optional parameters
  # @return [Sms]
  describe 'sms_send test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
