=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for YCloudApiClient::VerifyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VerifyApi' do
  before do
    # run before each test
    @api_instance = YCloudApiClient::VerifyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VerifyApi' do
    it 'should create an instance of VerifyApi' do
      expect(@api_instance).to be_instance_of(YCloudApiClient::VerifyApi)
    end
  end

  # unit tests for verification_check
  # Check a verification
  # Checks a verification with a phone number, an email address, or a verification ID. A &#x60;pending&#x60; verification status changes to &#x60;approved&#x60; once you receive a response with the &#x60;valid&#x60; parameter is &#x60;true&#x60;. An approved verification cannot be checked anymore.
  # @param verification_check_request 
  # @param [Hash] opts the optional parameters
  # @return [VerificationCheck]
  describe 'verification_check test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for verification_send
  # Start a verification
  # Starts a verification by sending an SMS, voice, or email message to the recipient. This verification is charged once the message is sent successfully.
  # @param verification_send_request Verification request that needs to be sent.
  # @param [Hash] opts the optional parameters
  # @return [Verification]
  describe 'verification_send test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
