=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for YCloudApiClient::WhatsAppMessagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WhatsAppMessagesApi' do
  before do
    # run before each test
    @api_instance = YCloudApiClient::WhatsAppMessagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WhatsAppMessagesApi' do
    it 'should create an instance of WhatsAppMessagesApi' do
      expect(@api_instance).to be_instance_of(YCloudApiClient::WhatsAppMessagesApi)
    end
  end

  # unit tests for whatsapp_message_retrieve
  # Retrieve a WhatsApp message
  # Retrieves a WhatsApp message you&#39;ve previously sent.
  # @param id ID of the object.
  # @param [Hash] opts the optional parameters
  # @return [WhatsappMessage]
  describe 'whatsapp_message_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for whatsapp_message_send
  # Send a WhatsApp message
  # Sends an outbound WhatsApp message.
  # @param whatsapp_message_send_request 
  # @param [Hash] opts the optional parameters
  # @return [WhatsappMessage]
  describe 'whatsapp_message_send test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
