=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'cgi'

module YCloudApiClient
  class VoicesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List voice records
    # Returns a paginated list of voice calls you've previously sent.
    # @param [Hash] opts the parameters
    # @option opts [Integer] :page Page number of the results to be returned, 1-based. (default to 1)
    # @option opts [Integer] :limit A limit on the number of results to be returned, or number of results per page, between 1 and 100, defaults to 10. (default to 10)
    # @option opts [Boolean] :include_total Return results inside an object that contains the total result count or not. (default to false)
    # @option opts [Time] :filter_create_time_gte Return results where the &#x60;createTime&#x60; field is greater than or equal to this value. Default: One day ago from now.
    # @option opts [Time] :filter_create_time_lte Return results where the &#x60;createTime&#x60; field is less than or equal to this value.
    # @option opts [String] :filter_id Unique object ID on our side. Other filter parameters will be ignored if this parameter is present.
    # @return [VoicePage]
    def voice_list(opts = {})
      data, _status_code, _headers = voice_list_with_http_info(opts)
      data
    end

    # List voice records
    # Returns a paginated list of voice calls you&#39;ve previously sent.
    # @param [Hash] opts the parameters
    # @option opts [Integer] :page Page number of the results to be returned, 1-based. (default to 1)
    # @option opts [Integer] :limit A limit on the number of results to be returned, or number of results per page, between 1 and 100, defaults to 10. (default to 10)
    # @option opts [Boolean] :include_total Return results inside an object that contains the total result count or not. (default to false)
    # @option opts [Time] :filter_create_time_gte Return results where the &#x60;createTime&#x60; field is greater than or equal to this value. Default: One day ago from now.
    # @option opts [Time] :filter_create_time_lte Return results where the &#x60;createTime&#x60; field is less than or equal to this value.
    # @option opts [String] :filter_id Unique object ID on our side. Other filter parameters will be ignored if this parameter is present.
    # @return [Array<(VoicePage, Integer, Hash)>] VoicePage data, response status code and response headers
    def voice_list_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: VoicesApi.voice_list ...'
      end
      # unbox the parameters from the hash
      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] > 100
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling VoicesApi.voice_list, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling VoicesApi.voice_list, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] > 100
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling VoicesApi.voice_list, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] < 1
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling VoicesApi.voice_list, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/voices'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'includeTotal'] = opts[:'include_total'] if !opts[:'include_total'].nil?
      query_params[:'filter.createTime.gte'] = opts[:'filter_create_time_gte'] if !opts[:'filter_create_time_gte'].nil?
      query_params[:'filter.createTime.lte'] = opts[:'filter_create_time_lte'] if !opts[:'filter_create_time_lte'].nil?
      query_params[:'filter.id'] = opts[:'filter_id'] if !opts[:'filter_id'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'VoicePage'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['api_key']

      new_options = opts.merge(
        :operation => :"VoicesApi.voice_list",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: VoicesApi#voice_list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Send a voice code
    # Sends an outbound voice call verification code.
    # @param voice_send_request [VoiceSendRequest] Voice call request that needs to be sent.
    # @param [Hash] opts the optional parameters
    # @return [Voice]
    def voice_send(voice_send_request, opts = {})
      data, _status_code, _headers = voice_send_with_http_info(voice_send_request, opts)
      data
    end

    # Send a voice code
    # Sends an outbound voice call verification code.
    # @param voice_send_request [VoiceSendRequest] Voice call request that needs to be sent.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Voice, Integer, Hash)>] Voice data, response status code and response headers
    def voice_send_with_http_info(voice_send_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: VoicesApi.voice_send ...'
      end
      # verify the required parameter 'voice_send_request' is set
      if @api_client.config.client_side_validation && voice_send_request.nil?
        fail ArgumentError, "Missing the required parameter 'voice_send_request' when calling VoicesApi.voice_send"
      end
      # resource path
      local_var_path = '/voices'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(voice_send_request)

      # return_type
      return_type = opts[:debug_return_type] || 'Voice'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['api_key']

      new_options = opts.merge(
        :operation => :"VoicesApi.voice_send",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: VoicesApi#voice_send\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
