=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for YCloudApiClient::WhatsappInboundMessageInteractiveButtonReply
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe YCloudApiClient::WhatsappInboundMessageInteractiveButtonReply do
  let(:instance) { YCloudApiClient::WhatsappInboundMessageInteractiveButtonReply.new }

  describe 'test an instance of WhatsappInboundMessageInteractiveButtonReply' do
    it 'should create an instance of WhatsappInboundMessageInteractiveButtonReply' do
      expect(instance).to be_instance_of(YCloudApiClient::WhatsappInboundMessageInteractiveButtonReply)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
