=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

# Common files
require 'ycloud_api/api_client'
require 'ycloud_api/api_error'
require 'ycloud_api/version'
require 'ycloud_api/configuration'

# Models
require 'ycloud_api/models/balance'
require 'ycloud_api/models/email'
require 'ycloud_api/models/email_content_type'
require 'ycloud_api/models/email_delivery'
require 'ycloud_api/models/email_send_request'
require 'ycloud_api/models/error'
require 'ycloud_api/models/error_response'
require 'ycloud_api/models/event'
require 'ycloud_api/models/event_type'
require 'ycloud_api/models/mailbox'
require 'ycloud_api/models/page'
require 'ycloud_api/models/sms'
require 'ycloud_api/models/sms_page'
require 'ycloud_api/models/sms_send_request'
require 'ycloud_api/models/verification'
require 'ycloud_api/models/verification_channel'
require 'ycloud_api/models/verification_check'
require 'ycloud_api/models/verification_check_request'
require 'ycloud_api/models/verification_send_request'
require 'ycloud_api/models/verification_status'
require 'ycloud_api/models/voice'
require 'ycloud_api/models/voice_page'
require 'ycloud_api/models/voice_send_request'
require 'ycloud_api/models/webhook_endpoint'
require 'ycloud_api/models/webhook_endpoint_create_request'
require 'ycloud_api/models/webhook_endpoint_page'
require 'ycloud_api/models/webhook_endpoint_status'
require 'ycloud_api/models/webhook_endpoint_update_request'
require 'ycloud_api/models/whatsapp_inbound_message'
require 'ycloud_api/models/whatsapp_inbound_message_button'
require 'ycloud_api/models/whatsapp_inbound_message_interactive'
require 'ycloud_api/models/whatsapp_inbound_message_interactive_button_reply'
require 'ycloud_api/models/whatsapp_inbound_message_interactive_list_reply'
require 'ycloud_api/models/whatsapp_inbound_message_location'
require 'ycloud_api/models/whatsapp_inbound_message_media'
require 'ycloud_api/models/whatsapp_inbound_message_text'
require 'ycloud_api/models/whatsapp_inbound_message_type'
require 'ycloud_api/models/whatsapp_message'
require 'ycloud_api/models/whatsapp_message_contact'
require 'ycloud_api/models/whatsapp_message_contact_addresses_inner'
require 'ycloud_api/models/whatsapp_message_contact_emails_inner'
require 'ycloud_api/models/whatsapp_message_contact_name'
require 'ycloud_api/models/whatsapp_message_contact_org'
require 'ycloud_api/models/whatsapp_message_contact_phones_inner'
require 'ycloud_api/models/whatsapp_message_contact_urls_inner'
require 'ycloud_api/models/whatsapp_message_interactive'
require 'ycloud_api/models/whatsapp_message_interactive_action'
require 'ycloud_api/models/whatsapp_message_interactive_action_buttons_inner'
require 'ycloud_api/models/whatsapp_message_interactive_action_buttons_inner_reply'
require 'ycloud_api/models/whatsapp_message_interactive_action_sections_inner'
require 'ycloud_api/models/whatsapp_message_interactive_action_sections_inner_rows_inner'
require 'ycloud_api/models/whatsapp_message_interactive_body'
require 'ycloud_api/models/whatsapp_message_interactive_footer'
require 'ycloud_api/models/whatsapp_message_interactive_header'
require 'ycloud_api/models/whatsapp_message_location'
require 'ycloud_api/models/whatsapp_message_media'
require 'ycloud_api/models/whatsapp_message_send_request'
require 'ycloud_api/models/whatsapp_message_status'
require 'ycloud_api/models/whatsapp_message_template'
require 'ycloud_api/models/whatsapp_message_template_components_inner'
require 'ycloud_api/models/whatsapp_message_template_components_inner_parameters_inner'
require 'ycloud_api/models/whatsapp_message_template_language'
require 'ycloud_api/models/whatsapp_message_text'
require 'ycloud_api/models/whatsapp_message_type'
require 'ycloud_api/models/whatsapp_phone_number'
require 'ycloud_api/models/whatsapp_phone_number_code_verification_status'
require 'ycloud_api/models/whatsapp_phone_number_name_status'
require 'ycloud_api/models/whatsapp_phone_number_page'
require 'ycloud_api/models/whatsapp_phone_number_quality_rating'
require 'ycloud_api/models/whatsapp_phone_number_status'
require 'ycloud_api/models/whatsapp_template'
require 'ycloud_api/models/whatsapp_template_category'
require 'ycloud_api/models/whatsapp_template_component'
require 'ycloud_api/models/whatsapp_template_component_button'
require 'ycloud_api/models/whatsapp_template_component_button_type'
require 'ycloud_api/models/whatsapp_template_component_example'
require 'ycloud_api/models/whatsapp_template_create_request'
require 'ycloud_api/models/whatsapp_template_page'
require 'ycloud_api/models/whatsapp_template_status'

# APIs
require 'ycloud_api/api/balance_api'
require 'ycloud_api/api/emails_api'
require 'ycloud_api/api/sms_api'
require 'ycloud_api/api/verify_api'
require 'ycloud_api/api/voices_api'
require 'ycloud_api/api/webhook_endpoints_api'
require 'ycloud_api/api/whats_app_messages_api'
require 'ycloud_api/api/whats_app_phone_numbers_api'
require 'ycloud_api/api/whats_app_templates_api'

module YCloudApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   YCloudApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
