=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'date'
require 'time'

module YCloudApiClient
  class EventType
    EMAIL_DELIVERY_UPDATED = "email.delivery.updated".freeze
    SMS_MESSAGE_UPDATED = "sms.message.updated".freeze
    VOICE_MESSAGE_UPDATED = "voice.message.updated".freeze
    WHATSAPP_INBOUND_MESSAGE_RECEIVED = "whatsapp.inbound_message.received".freeze
    WHATSAPP_MESSAGE_UPDATED = "whatsapp.message.updated".freeze
    WHATSAPP_PHONE_NUMBER_NAME_UPDATED = "whatsapp.phone_number.name_updated".freeze
    WHATSAPP_PHONE_NUMBER_QUALITY_UPDATED = "whatsapp.phone_number.quality_updated".freeze
    WHATSAPP_TEMPLATE_REVIEWED = "whatsapp.template.reviewed".freeze

    def self.all_vars
      @all_vars ||= [EMAIL_DELIVERY_UPDATED, SMS_MESSAGE_UPDATED, VOICE_MESSAGE_UPDATED, WHATSAPP_INBOUND_MESSAGE_RECEIVED, WHATSAPP_MESSAGE_UPDATED, WHATSAPP_PHONE_NUMBER_NAME_UPDATED, WHATSAPP_PHONE_NUMBER_QUALITY_UPDATED, WHATSAPP_TEMPLATE_REVIEWED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EventType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EventType"
    end
  end
end
