=begin
#YCloud API

#The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

The version of the OpenAPI document: v2
Contact: service@ycloud.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'date'
require 'time'

module YCloudApiClient
  class WhatsappPhoneNumberStatus
    PENDING = "PENDING".freeze
    UNVERIFIED = "UNVERIFIED".freeze
    MANUAL_REVIEW = "MANUAL_REVIEW".freeze
    DISCONNECTED = "DISCONNECTED".freeze
    CONNECTED = "CONNECTED".freeze
    FLAGGED = "FLAGGED".freeze
    WARNED = "WARNED".freeze
    RATE_LIMITED = "RATE_LIMITED".freeze
    BANNED = "BANNED".freeze
    RESTRICTED = "RESTRICTED".freeze
    BLOCKED = "BLOCKED".freeze
    MIGRATED = "MIGRATED".freeze
    UNKNOWN = "UNKNOWN".freeze

    def self.all_vars
      @all_vars ||= [PENDING, UNVERIFIED, MANUAL_REVIEW, DISCONNECTED, CONNECTED, FLAGGED, WARNED, RATE_LIMITED, BANNED, RESTRICTED, BLOCKED, MIGRATED, UNKNOWN].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WhatsappPhoneNumberStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WhatsappPhoneNumberStatus"
    end
  end
end
